-- 재귀 CTE 사용.
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT HS.HOUR AS HOUR, COUNT(AO.ANIMAL_id) AS COUNT
FROM HOURS HS
         LEFT OUTER JOIN ANIMAL_OUTS AO
                         ON HS.HOUR = HOUR(AO.DATETIME)
GROUP BY HS.HOUR
ORDER BY HS.HOUR;

-- UNION ALL 사용.
SELECT HS.HOUR AS HOUR, COUNT(AO.ANIMAL_id) AS COUNT
FROM (
         SELECT 0 AS hour UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL
         SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
         SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL
         SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL
         SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL
         SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL
         SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL
         SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
     ) AS HS
         LEFT OUTER JOIN ANIMAL_OUTS AO
                         ON HS.HOUR = HOUR(AO.DATETIME)
GROUP BY HS.HOUR
ORDER BY HS.HOUR;