SELECT CRCRH.HISTORY_ID AS HISTORY_ID
     , ROUND(CRCC.DAILY_FEE * (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) * (1 - IFNULL(CRCDP.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
AND CRCDP.DURATION_TYPE =
    CASE
       WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
       WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
       WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    END
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CRCRH.HISTORY_ID DESC;

-- 다시 풀어보기.