SELECT B.APNT_NO, A.PT_NAME, B.PT_NO, C.MCDP_CD, C.DR_NAME, B.APNT_YMD
FROM PATIENT A
INNER JOIN APPOINTMENT B
ON A.PT_NO = B.PT_NO
INNER JOIN DOCTOR C
ON B.MDDR_ID = C.DR_ID
WHERE C.MCDP_CD = 'CS' AND B.APNT_CNCL_YN = 'N' AND DATE(B.APNT_YMD) = '2022-04-13'
ORDER BY B.APNT_YMD ASC;