SELECT CHILD_ECOLI.ID, CHILD_ECOLI.GENOTYPE, PARENT_ECOLI.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA PARENT_ECOLI
JOIN ECOLI_DATA CHILD_ECOLI
ON PARENT_ECOLI.ID = CHILD_ECOLI.PARENT_ID
WHERE (PARENT_ECOLI.GENOTYPE & CHILD_ECOLI.GENOTYPE) = PARENT_ECOLI.GENOTYPE
ORDER BY CHILD_ECOLI.ID ASC