SELECT EDSUB.YEAR AS YEAR, EDSUB.MAX_SIZE - ED.SIZE_OF_COLONY AS YEAR_DEV, ED.ID AS ID
FROM ECOLI_DATA ED
JOIN (
        SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
     ) EDSUB
ON YEAR(ED.DIFFERENTIATION_DATE) = EDSUB.YEAR
ORDER BY YEAR(ED.DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC