SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%M-%d') AS PUBLISHED_DATE
FROM book A
         INNER JOIN AUTHOR B
                    ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE category = '경제'
ORDER BY PUBLISHED_DATE ASC;