SELECT A.USER_ID
     , A.NICKNAME
     , CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS '전체주소'
     , CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER A
INNER JOIN USED_GOODS_BOARD B
ON A.USER_ID = B.WRITER_ID
GROUP BY A.USER_ID
HAVING COUNT(A.USER_ID) >= 3
ORDER BY A.USER_ID DESC;