SELECT A.category, SUM(SALES) AS TOTAL_SALES
FROM BOOK A
         INNER JOIN BOOK_SALES B
                    ON A.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY A.category
ORDER BY A.category ASC